[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-json-data-source"
version = "0.0.1"
description = "JSON data source plugin for graph visualization"
dependencies = ["graph-api>=0.0.1"]

[project.entry-points."graph.data_source"]
json_data_source = "json_data_source.json_data_source:JsonDataSource"

[tool.setuptools.data-files]
data = ["*.json"]